/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Monitoring Server API
 * OpenAPI spec version: 1.0
 */
import type {
  Agent,
  AgentConfigBody,
  AgentSpecs,
  CreateAgent400,
  CreateAgent404,
  CreateAgent500,
  CreateAgentBody,
  CreateAgentResponse,
  GetAgentByID400,
  GetAgentByID404,
  GetAgentByID500,
  GetAgentSpecs400,
  GetAgentSpecs404,
  GetAgentSpecs500,
  GetAllAgents400,
  GetAllAgents404,
  GetAllAgents500,
  GetStreamFrames400,
  GetStreamFrames404,
  GetStreamFrames500
} from '../models';


export type getAllAgentsResponse200 = {
  data: Agent[]
  status: 200
}

export type getAllAgentsResponse400 = {
  data: GetAllAgents400
  status: 400
}

export type getAllAgentsResponse404 = {
  data: GetAllAgents404
  status: 404
}

export type getAllAgentsResponse500 = {
  data: GetAllAgents500
  status: 500
}

export type getAllAgentsResponseSuccess = (getAllAgentsResponse200) & {
  headers: Headers;
};
export type getAllAgentsResponseError = (getAllAgentsResponse400 | getAllAgentsResponse404 | getAllAgentsResponse500) & {
  headers: Headers;
};

export type getAllAgentsResponse = (getAllAgentsResponseSuccess | getAllAgentsResponseError)

export const getGetAllAgentsUrl = () => {




  return `http://127.0.0.1:8091/api/v1/agents`
}

/**
 * @summary Get all agents
 */
export const getAllAgents = async ( options?: RequestInit): Promise<getAllAgentsResponse> => {

  const res = await fetch(getGetAllAgentsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAllAgentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllAgentsResponse
}



export type createAgentResponse200 = {
  data: CreateAgentResponse
  status: 200
}

export type createAgentResponse400 = {
  data: CreateAgent400
  status: 400
}

export type createAgentResponse404 = {
  data: CreateAgent404
  status: 404
}

export type createAgentResponse500 = {
  data: CreateAgent500
  status: 500
}

export type createAgentResponseSuccess = (createAgentResponse200) & {
  headers: Headers;
};
export type createAgentResponseError = (createAgentResponse400 | createAgentResponse404 | createAgentResponse500) & {
  headers: Headers;
};

export type createAgentResponse = (createAgentResponseSuccess | createAgentResponseError)

export const getCreateAgentUrl = () => {




  return `http://127.0.0.1:8091/api/v1/agents`
}

/**
 * @summary Create new agent
 */
export const createAgent = async (createAgentBody: CreateAgentBody, options?: RequestInit): Promise<createAgentResponse> => {

  const res = await fetch(getCreateAgentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createAgentBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createAgentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createAgentResponse
}



export type getAgentByIDResponse200 = {
  data: Agent
  status: 200
}

export type getAgentByIDResponse400 = {
  data: GetAgentByID400
  status: 400
}

export type getAgentByIDResponse404 = {
  data: GetAgentByID404
  status: 404
}

export type getAgentByIDResponse500 = {
  data: GetAgentByID500
  status: 500
}

export type getAgentByIDResponseSuccess = (getAgentByIDResponse200) & {
  headers: Headers;
};
export type getAgentByIDResponseError = (getAgentByIDResponse400 | getAgentByIDResponse404 | getAgentByIDResponse500) & {
  headers: Headers;
};

export type getAgentByIDResponse = (getAgentByIDResponseSuccess | getAgentByIDResponseError)

export const getGetAgentByIDUrl = (agentID: string,) => {




  return `http://127.0.0.1:8091/api/v1/agents/${agentID}`
}

/**
 * @summary Get agent by ID
 */
export const getAgentByID = async (agentID: string, options?: RequestInit): Promise<getAgentByIDResponse> => {

  const res = await fetch(getGetAgentByIDUrl(agentID),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAgentByIDResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAgentByIDResponse
}



export type getStreamFramesResponse200 = {
  data: Blob
  status: 200
}

export type getStreamFramesResponse400 = {
  data: GetStreamFrames400
  status: 400
}

export type getStreamFramesResponse404 = {
  data: GetStreamFrames404
  status: 404
}

export type getStreamFramesResponse500 = {
  data: GetStreamFrames500
  status: 500
}

export type getStreamFramesResponseSuccess = (getStreamFramesResponse200) & {
  headers: Headers;
};
export type getStreamFramesResponseError = (getStreamFramesResponse400 | getStreamFramesResponse404 | getStreamFramesResponse500) & {
  headers: Headers;
};

export type getStreamFramesResponse = (getStreamFramesResponseSuccess | getStreamFramesResponseError)

export const getGetStreamFramesUrl = (agentID: string,) => {




  return `http://127.0.0.1:8091/api/v1/agents/${agentID}/frames`
}

/**
 * @summary Get stream frames
 */
export const getStreamFrames = async (agentID: string, options?: RequestInit): Promise<getStreamFramesResponse> => {

  const res = await fetch(getGetStreamFramesUrl(agentID),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.blob();
  const data: getStreamFramesResponse['data'] = body as getStreamFramesResponse['data']
  return { data, status: res.status, headers: res.headers } as getStreamFramesResponse
}



export type downloadAgentFilesResponse200 = {
  data: Blob
  status: 200
}

export type downloadAgentFilesResponse400 = {
  data: Blob
  status: 400
}

export type downloadAgentFilesResponse404 = {
  data: Blob
  status: 404
}

export type downloadAgentFilesResponse500 = {
  data: Blob
  status: 500
}

export type downloadAgentFilesResponseSuccess = (downloadAgentFilesResponse200) & {
  headers: Headers;
};
export type downloadAgentFilesResponseError = (downloadAgentFilesResponse400 | downloadAgentFilesResponse404 | downloadAgentFilesResponse500) & {
  headers: Headers;
};

export type downloadAgentFilesResponse = (downloadAgentFilesResponseSuccess | downloadAgentFilesResponseError)

export const getDownloadAgentFilesUrl = (agentID: string,) => {




  return `http://127.0.0.1:8091/api/v1/agents/${agentID}/setupconfig`
}

/**
 * @summary Download agent files
 */
export const downloadAgentFiles = async (agentID: string,
    agentConfigBody: AgentConfigBody, options?: RequestInit): Promise<downloadAgentFilesResponse> => {

  const res = await fetch(getDownloadAgentFilesUrl(agentID),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(agentConfigBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.blob();
  const data: downloadAgentFilesResponse['data'] = body as downloadAgentFilesResponse['data']
  return { data, status: res.status, headers: res.headers } as downloadAgentFilesResponse
}



export type getAgentSpecsResponse200 = {
  data: AgentSpecs
  status: 200
}

export type getAgentSpecsResponse400 = {
  data: GetAgentSpecs400
  status: 400
}

export type getAgentSpecsResponse404 = {
  data: GetAgentSpecs404
  status: 404
}

export type getAgentSpecsResponse500 = {
  data: GetAgentSpecs500
  status: 500
}

export type getAgentSpecsResponseSuccess = (getAgentSpecsResponse200) & {
  headers: Headers;
};
export type getAgentSpecsResponseError = (getAgentSpecsResponse400 | getAgentSpecsResponse404 | getAgentSpecsResponse500) & {
  headers: Headers;
};

export type getAgentSpecsResponse = (getAgentSpecsResponseSuccess | getAgentSpecsResponseError)

export const getGetAgentSpecsUrl = (agentID: string,) => {




  return `http://127.0.0.1:8091/api/v1/agents/${agentID}/specifications`
}

/**
 * @summary Get agent specifications
 */
export const getAgentSpecs = async (agentID: string, options?: RequestInit): Promise<getAgentSpecsResponse> => {

  const res = await fetch(getGetAgentSpecsUrl(agentID),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAgentSpecsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAgentSpecsResponse
}



