/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Monitoring Server API
 * OpenAPI spec version: 1.0
 */
import type {
  Agent,
  AgentConfigBody,
  AgentGroup,
  AgentSpecs,
  AgentsOverview,
  CreateAgentBody,
  CreateAgentGroupBody,
  CreateAgentResponse,
  UpdateAgentGroupBody
} from '../models';

import { customFetch } from '../apiFetch';

export const getGetAllAgentsUrl = () => {




  return `/api/v1/agents`
}

/**
 * @summary Get all agents
 */
export const getAllAgents = async ( options?: Parameters<typeof customFetch>[1]): Promise<Agent[]> => {

  return customFetch<Agent[]>(getGetAllAgentsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateAgentUrl = () => {




  return `/api/v1/agents`
}

/**
 * @summary Create new agent
 */
export const createAgent = async (createAgentBody: CreateAgentBody, options?: Parameters<typeof customFetch>[1]): Promise<CreateAgentResponse> => {

  return customFetch<CreateAgentResponse>(getCreateAgentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createAgentBody)
  }
);}



export const getGetAgentByIDUrl = (agentID: string,) => {




  return `/api/v1/agents/${agentID}`
}

/**
 * @summary Get agent by ID
 */
export const getAgentByID = async (agentID: string, options?: Parameters<typeof customFetch>[1]): Promise<Agent> => {

  return customFetch<Agent>(getGetAgentByIDUrl(agentID),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetStreamFramesUrl = (agentID: string,) => {




  return `/api/v1/agents/${agentID}/frames`
}

/**
 * @summary Get stream frames
 */
export const getStreamFrames = async (agentID: string, options?: Parameters<typeof customFetch>[1]): Promise<Blob> => {

  return customFetch<Blob>(getGetStreamFramesUrl(agentID),
  {
    ...options,
    method: 'GET'


  }
);}



export const getDownloadAgentFilesUrl = (agentID: string,) => {




  return `/api/v1/agents/${agentID}/setupconfig`
}

/**
 * @summary Download agent files
 */
export const downloadAgentFiles = async (agentID: string,
    agentConfigBody: AgentConfigBody, options?: Parameters<typeof customFetch>[1]): Promise<Blob> => {

  return customFetch<Blob>(getDownloadAgentFilesUrl(agentID),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(agentConfigBody)
  }
);}



export const getGetAgentSpecsUrl = (agentID: string,) => {




  return `/api/v1/agents/${agentID}/specifications`
}

/**
 * @summary Get agent specifications
 */
export const getAgentSpecs = async (agentID: string, options?: Parameters<typeof customFetch>[1]): Promise<AgentSpecs> => {

  return customFetch<AgentSpecs>(getGetAgentSpecsUrl(agentID),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetFleetOverviewUrl = () => {




  return `/api/v1/fleet/overview`
}

/**
 * @summary Get fleet overview
 */
export const getFleetOverview = async ( options?: Parameters<typeof customFetch>[1]): Promise<AgentsOverview> => {

  return customFetch<AgentsOverview>(getGetFleetOverviewUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetAllAgentGroupsUrl = () => {




  return `/api/v1/groups`
}

/**
 * @summary Get all agent groups
 */
export const getAllAgentGroups = async ( options?: Parameters<typeof customFetch>[1]): Promise<AgentGroup[]> => {

  return customFetch<AgentGroup[]>(getGetAllAgentGroupsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateAgentGroupUrl = () => {




  return `/api/v1/groups`
}

/**
 * @summary Create new agent group
 */
export const createAgentGroup = async (createAgentGroupBody: CreateAgentGroupBody, options?: Parameters<typeof customFetch>[1]): Promise<AgentGroup> => {

  return customFetch<AgentGroup>(getCreateAgentGroupUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createAgentGroupBody)
  }
);}



export const getGetAgentGroupByIDUrl = (id: string,) => {




  return `/api/v1/groups/${id}`
}

/**
 * @summary Get agent group by ID
 */
export const getAgentGroupByID = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<AgentGroup> => {

  return customFetch<AgentGroup>(getGetAgentGroupByIDUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getDeleteAgentGroupUrl = (id: string,) => {




  return `/api/v1/groups/${id}`
}

/**
 * @summary Delete agent group by ID
 */
export const deleteAgentGroup = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<void> => {

  return customFetch<void>(getDeleteAgentGroupUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getUpdateAgentGroupUrl = (id: string,) => {




  return `/api/v1/groups/${id}`
}

/**
 * @summary Update agent group
 */
export const updateAgentGroup = async (id: string,
    updateAgentGroupBody: UpdateAgentGroupBody, options?: Parameters<typeof customFetch>[1]): Promise<void> => {

  return customFetch<void>(getUpdateAgentGroupUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateAgentGroupBody)
  }
);}



