/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Monitoring Server API
 * OpenAPI spec version: 1.0
 */
import type {
  Agent,
  CreateAgentBody,
  CreateAgentResponse,
  GinH
} from '../models';


export type getAgentsResponse200 = {
  data: Agent[]
  status: 200
}

export type getAgentsResponse400 = {
  data: GinH
  status: 400
}

export type getAgentsResponse404 = {
  data: GinH
  status: 404
}

export type getAgentsResponse500 = {
  data: GinH
  status: 500
}

export type getAgentsResponseSuccess = (getAgentsResponse200) & {
  headers: Headers;
};
export type getAgentsResponseError = (getAgentsResponse400 | getAgentsResponse404 | getAgentsResponse500) & {
  headers: Headers;
};

export type getAgentsResponse = (getAgentsResponseSuccess | getAgentsResponseError)

export const getGetAgentsUrl = () => {




  return `http://127.0.0.1:8091/api/v1/agents`
}

/**
 * @summary Get all agents
 */
export const getAgents = async ( options?: RequestInit): Promise<getAgentsResponse> => {

  const res = await fetch(getGetAgentsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAgentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAgentsResponse
}



export type postAgentsResponse200 = {
  data: CreateAgentResponse
  status: 200
}

export type postAgentsResponse400 = {
  data: GinH
  status: 400
}

export type postAgentsResponse404 = {
  data: GinH
  status: 404
}

export type postAgentsResponse500 = {
  data: GinH
  status: 500
}

export type postAgentsResponseSuccess = (postAgentsResponse200) & {
  headers: Headers;
};
export type postAgentsResponseError = (postAgentsResponse400 | postAgentsResponse404 | postAgentsResponse500) & {
  headers: Headers;
};

export type postAgentsResponse = (postAgentsResponseSuccess | postAgentsResponseError)

export const getPostAgentsUrl = () => {




  return `http://127.0.0.1:8091/api/v1/agents`
}

/**
 * @summary Create new agent
 */
export const postAgents = async (createAgentBody: CreateAgentBody, options?: RequestInit): Promise<postAgentsResponse> => {

  const res = await fetch(getPostAgentsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createAgentBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postAgentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postAgentsResponse
}



