// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agents": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get all agents",
                "operationId": "getAllAgents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Agent"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create new agent",
                "operationId": "createAgent",
                "parameters": [
                    {
                        "description": "Create agent body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateAgentBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CreateAgentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/agents/{agentID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get agent by ID",
                "operationId": "getAgentByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Agent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/agents/{agentID}/frames": {
            "get": {
                "produces": [
                    "image/jpeg"
                ],
                "summary": "Get stream frames",
                "operationId": "getStreamFrames",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/agents/{agentID}/setupconfig": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/zip"
                ],
                "summary": "Download agent files",
                "operationId": "downloadAgentFiles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Download agent files",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AgentConfigBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/agents/{agentID}/specifications": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get agent specifications",
                "operationId": "getAgentSpecs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AgentSpecs"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Agent": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isOnline": {
                    "type": "boolean"
                },
                "lastSeenAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "AgentConfigBody": {
            "type": "object",
            "properties": {
                "enrollmentKey": {
                    "type": "string"
                }
            }
        },
        "AgentSpecs": {
            "type": "object",
            "properties": {
                "agentId": {
                    "type": "string"
                },
                "cpuSpecs": {
                    "$ref": "#/definitions/CpuSpecs"
                },
                "diskSpecs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DiskSpecs"
                    }
                },
                "hostSpecs": {
                    "$ref": "#/definitions/HostSpecs"
                },
                "memorySpecs": {
                    "$ref": "#/definitions/MemorySpecs"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "CpuSpecs": {
            "type": "object",
            "properties": {
                "architecture": {
                    "type": "string"
                },
                "availability": {
                    "type": "string"
                },
                "currentClockSpeed": {
                    "type": "integer"
                },
                "data_width": {
                    "type": "integer"
                },
                "l2CacheSize": {
                    "type": "integer"
                },
                "l3CacheSize": {
                    "type": "integer"
                },
                "manufacturer": {
                    "type": "string"
                },
                "maxClockSpeed": {
                    "type": "integer"
                },
                "modelName": {
                    "type": "string"
                },
                "numberOfCores": {
                    "type": "integer"
                },
                "numberOfEnabledCores": {
                    "type": "integer"
                },
                "numberOfLogicalProcessors": {
                    "type": "integer"
                },
                "processorId": {
                    "type": "string"
                },
                "socketDesignation": {
                    "type": "string"
                },
                "stepping": {
                    "type": "string"
                },
                "virtualizationFirmwareEnabled": {
                    "type": "boolean"
                }
            }
        },
        "CreateAgentBody": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "CreateAgentResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "enrollmentKey": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isOnline": {
                    "type": "boolean"
                },
                "lastSeenAt": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "DiskSpecs": {
            "type": "object",
            "properties": {
                "device": {
                    "type": "string"
                },
                "fsType": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "HostSpecs": {
            "type": "object",
            "properties": {
                "hostname": {
                    "type": "string"
                },
                "kernelVersion": {
                    "type": "string"
                },
                "os": {
                    "type": "string"
                },
                "osArch": {
                    "type": "string"
                },
                "osType": {
                    "type": "string"
                },
                "osVersion": {
                    "type": "string"
                }
            }
        },
        "MemorySpecs": {
            "type": "object",
            "properties": {
                "physicalMemoryInfo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/PhysicalMemoryInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "PhysicalMemoryInfo": {
            "type": "object",
            "properties": {
                "bankLabel": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "configuredClockSpeed": {
                    "type": "integer"
                },
                "deviceLocator": {
                    "type": "string"
                },
                "form_factor": {
                    "type": "string"
                },
                "hotSwappable": {
                    "type": "boolean"
                },
                "manufacturer": {
                    "type": "string"
                },
                "memoryType": {
                    "type": "string"
                },
                "modelName": {
                    "type": "string"
                },
                "removable": {
                    "type": "boolean"
                },
                "replaceable": {
                    "type": "boolean"
                },
                "serialNumber": {
                    "type": "string"
                },
                "speed": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8091",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Monitoring Server API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
