basePath: /api/v1
definitions:
  Agent:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      isOnline:
        type: boolean
      lastSeenAt:
        type: string
      name:
        type: string
      status:
        type: string
    type: object
  AgentConfigBody:
    properties:
      enrollmentKey:
        type: string
    type: object
  AgentConfigResponse:
    properties:
      enrollmentAddress:
        type: string
      enrollmentKey:
        type: string
      serverAddress:
        type: string
    type: object
  AgentSpecs:
    properties:
      agentId:
        type: string
      cpuSpecs:
        $ref: '#/definitions/CpuSpecs'
      diskSpecs:
        items:
          $ref: '#/definitions/DiskSpecs'
        type: array
      hostSpecs:
        $ref: '#/definitions/HostSpecs'
      memorySpecs:
        $ref: '#/definitions/MemorySpecs'
      updatedAt:
        type: string
    type: object
  CpuSpecs:
    properties:
      architecture:
        type: string
      availability:
        type: string
      currentClockSpeed:
        type: integer
      data_width:
        type: integer
      l2CacheSize:
        type: integer
      l3CacheSize:
        type: integer
      manufacturer:
        type: string
      maxClockSpeed:
        type: integer
      modelName:
        type: string
      numberOfCores:
        type: integer
      numberOfEnabledCores:
        type: integer
      numberOfLogicalProcessors:
        type: integer
      processorId:
        type: string
      socketDesignation:
        type: string
      stepping:
        type: string
      virtualizationFirmwareEnabled:
        type: boolean
    type: object
  CreateAgentBody:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  CreateAgentResponse:
    properties:
      createdAt:
        type: string
      description:
        type: string
      enrollmentKey:
        type: string
      id:
        type: string
      isOnline:
        type: boolean
      lastSeenAt:
        type: string
      name:
        type: string
      status:
        type: string
    type: object
  DiskSpecs:
    properties:
      device:
        type: string
      fsType:
        type: string
      total:
        type: integer
    type: object
  HostSpecs:
    properties:
      hostname:
        type: string
      kernelVersion:
        type: string
      os:
        type: string
      osArch:
        type: string
      osType:
        type: string
      osVersion:
        type: string
    type: object
  MemorySpecs:
    properties:
      physicalMemoryInfo:
        items:
          $ref: '#/definitions/PhysicalMemoryInfo'
        type: array
      total:
        type: integer
    type: object
  PhysicalMemoryInfo:
    properties:
      bankLabel:
        type: string
      capacity:
        type: integer
      configuredClockSpeed:
        type: integer
      deviceLocator:
        type: string
      form_factor:
        type: string
      hotSwappable:
        type: boolean
      manufacturer:
        type: string
      memoryType:
        type: string
      modelName:
        type: string
      removable:
        type: boolean
      replaceable:
        type: boolean
      serialNumber:
        type: string
      speed:
        type: integer
    type: object
host: localhost:8091
info:
  contact: {}
  title: Monitoring Server API
  version: "1.0"
paths:
  /agents:
    get:
      operationId: getAllAgents
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Agent'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all agents
    post:
      consumes:
      - application/json
      operationId: createAgent
      parameters:
      - description: Create agent body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/CreateAgentBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CreateAgentResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Create new agent
  /agents/{agentID}:
    get:
      operationId: getAgentByID
      parameters:
      - description: Agent ID
        in: path
        name: agentID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Agent'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get agent by ID
  /agents/{agentID}/frames:
    get:
      operationId: getStreamFrames
      parameters:
      - description: Agent ID
        in: path
        name: agentID
        required: true
        type: string
      produces:
      - image/jpeg
      responses:
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get stream frames
  /agents/{agentID}/setupconfig:
    post:
      consumes:
      - application/json
      operationId: downloadAgentConfig
      parameters:
      - description: Agent ID
        in: path
        name: agentID
        required: true
        type: string
      - description: Download agent config body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/AgentConfigBody'
      produces:
      - application/x-yaml
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AgentConfigResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Download agent setup config
  /agents/{agentID}/specifications:
    get:
      operationId: getAgentSpecs
      parameters:
      - description: Agent ID
        in: path
        name: agentID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/AgentSpecs'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get agent specifications
swagger: "2.0"
