/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Monitoring Agent API
 * OpenAPI spec version: 1.0
 */
import type {
  GetMetrics500,
  GetSpecs500,
  Metrics,
  Specs
} from '../models';


export type getMetricsResponse200 = {
  data: Metrics
  status: 200
}

export type getMetricsResponse500 = {
  data: GetMetrics500
  status: 500
}

export type getMetricsResponseSuccess = (getMetricsResponse200) & {
  headers: Headers;
};
export type getMetricsResponseError = (getMetricsResponse500) & {
  headers: Headers;
};

export type getMetricsResponse = (getMetricsResponseSuccess | getMetricsResponseError)

export const getGetMetricsUrl = () => {




  return `http://127.0.0.1:8088/metrics`
}

/**
 * @summary Current system metrics
 */
export const getMetrics = async ( options?: RequestInit): Promise<getMetricsResponse> => {

  const res = await fetch(getGetMetricsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMetricsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMetricsResponse
}



export type getSpecsResponse200 = {
  data: Specs
  status: 200
}

export type getSpecsResponse500 = {
  data: GetSpecs500
  status: 500
}

export type getSpecsResponseSuccess = (getSpecsResponse200) & {
  headers: Headers;
};
export type getSpecsResponseError = (getSpecsResponse500) & {
  headers: Headers;
};

export type getSpecsResponse = (getSpecsResponseSuccess | getSpecsResponseError)

export const getGetSpecsUrl = () => {




  return `http://127.0.0.1:8088/specs`
}

/**
 * @summary System specifications
 */
export const getSpecs = async ( options?: RequestInit): Promise<getSpecsResponse> => {

  const res = await fetch(getGetSpecsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSpecsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSpecsResponse
}



