/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Monitoring Server API
 * OpenAPI spec version: 1.0
 */

export interface CpuSpecs {
  architecture?: string;
  availability?: string;
  currentClockSpeed?: number;
  data_width?: number;
  l2CacheSize?: number;
  l3CacheSize?: number;
  manufacturer?: string;
  maxClockSpeed?: number;
  modelName?: string;
  numberOfCores?: number;
  numberOfEnabledCores?: number;
  numberOfLogicalProcessors?: number;
  processorId?: string;
  socketDesignation?: string;
  stepping?: string;
  virtualizationFirmwareEnabled?: boolean;
}
