/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Monitoring Server API
 * OpenAPI spec version: 1.0
 */

export interface GithubComNougghtMonitoringSystemServerInternalTransportDtoTypesAgentConfigResponse {
  enrollmentAddress?: string;
  enrollmentKey?: string;
  serverAddress?: string;
}
