/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Monitoring Server API
 * OpenAPI spec version: 1.0
 */

export interface HostSpecs {
  hostname?: string;
  kernelVersion?: string;
  os?: string;
  osArch?: string;
  osType?: string;
  osVersion?: string;
}
