/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Monitoring Server API
 * OpenAPI spec version: 1.0
 */

export * from './agent';
export * from './agentConfigBody';
export * from './agentConfigResponse';
export * from './agentSpecs';
export * from './cpuSpecs';
export * from './createAgent400';
export * from './createAgent404';
export * from './createAgent500';
export * from './createAgentBody';
export * from './createAgentResponse';
export * from './diskSpecs';
export * from './downloadAgentConfig400';
export * from './downloadAgentConfig404';
export * from './downloadAgentConfig500';
export * from './getAgentByID400';
export * from './getAgentByID404';
export * from './getAgentByID500';
export * from './getAgentSpecs400';
export * from './getAgentSpecs404';
export * from './getAgentSpecs500';
export * from './getAllAgents400';
export * from './getAllAgents404';
export * from './getAllAgents500';
export * from './getStreamFrames400';
export * from './getStreamFrames404';
export * from './getStreamFrames500';
export * from './hostSpecs';
export * from './memorySpecs';
export * from './physicalMemoryInfo';
