/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Monitoring Server API
 * OpenAPI spec version: 1.0
 */

export interface PhysicalMemoryInfo {
  bankLabel?: string;
  capacity?: number;
  configuredClockSpeed?: number;
  deviceLocator?: string;
  form_factor?: string;
  hotSwappable?: boolean;
  manufacturer?: string;
  memoryType?: string;
  modelName?: string;
  removable?: boolean;
  replaceable?: boolean;
  serialNumber?: string;
  speed?: number;
}
