/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Monitoring Agent API
 * OpenAPI spec version: 1.0
 */
import type { MetricsDiskUsage } from './metricsDiskUsage';
import type { Process } from './process';

export interface Metrics {
  cpuPercent?: number;
  diskUsage?: MetricsDiskUsage;
  downloadMbps?: number;
  focusedWindow?: string;
  memoryUsed?: number;
  processList?: Process[];
  timestamp?: string;
  uploadMbps?: number;
}
