/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Monitoring Agent API
 * OpenAPI spec version: 1.0
 */

/**
 * форм-фактор памяти
 */
export type PhysicalMemoryInfoFormFactor = typeof PhysicalMemoryInfoFormFactor[keyof typeof PhysicalMemoryInfoFormFactor];


export const PhysicalMemoryInfoFormFactor = {
  unknown: 'unknown',
  other: 'other',
  sip: 'sip',
  dip: 'dip',
  zip: 'zip',
  soj: 'soj',
  proprietary: 'proprietary',
  simm: 'simm',
  dimm: 'dimm',
  tsop: 'tsop',
  pga: 'pga',
  rimm: 'rimm',
  sodimm: 'sodimm',
  srimm: 'srimm',
  smd: 'smd',
  ssmp: 'ssmp',
  qfp: 'qfp',
  tqfp: 'tqfp',
  soic: 'soic',
  lcc: 'lcc',
  plcc: 'plcc',
  bga: 'bga',
  fpgba: 'fpgba',
  lga: 'lga',
} as const;
