/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Monitoring Agent API
 * OpenAPI spec version: 1.0
 */
import type { PhysicalMemoryInfoFormFactor } from './physicalMemoryInfoFormFactor';
import type { PhysicalMemoryInfoMemoryType } from './physicalMemoryInfoMemoryType';

export interface PhysicalMemoryInfo {
  /** подключение памяти */
  bankLabel?: string;
  /** объем */
  capacity?: number;
  /** настроенная частота памяти */
  configuredClockSpeed?: number;
  /** расположение памяти */
  deviceLocator?: string;
  /** форм-фактор памяти */
  formFactor?: PhysicalMemoryInfoFormFactor;
  /** можно менять память без выключения системы */
  hotSwappable?: boolean;
  /** производитель */
  manufacturer?: string;
  /** тип памяти */
  memoryType?: PhysicalMemoryInfoMemoryType;
  /** модель/партия памяти */
  modelName?: string;
  /** можно ли вынимать память */
  removable?: boolean;
  /** можно ли заменять память */
  replaceable?: boolean;
  /** серийный номер */
  serialNumber?: string;
  /** поддерживаемя частота памяти */
  speed?: number;
}
