/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Monitoring Agent API
 * OpenAPI spec version: 1.0
 */

export interface CpuSpecs {
  coreCount?: number;
  logicalCoreCount?: number;
  modelName?: string;
}
