/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Monitoring Agent API
 * OpenAPI spec version: 1.0
 */

/**
 * архитектура https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-processor
 */
export type CpuSpecsArchitecture = typeof CpuSpecsArchitecture[keyof typeof CpuSpecsArchitecture];


export const CpuSpecsArchitecture = {
  x86: 'x86',
  x64: 'x64',
  mips: 'mips',
  alpha: 'alpha',
  powerpc: 'powerpc',
  arm: 'arm',
  ia64: 'ia64',
  itanium: 'itanium',
  arm64: 'arm64',
  other: 'other',
} as const;
