/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Monitoring Agent API
 * OpenAPI spec version: 1.0
 */

export interface HostSpecs {
  /** имя хоста */
  hostName?: string;
  /** операционная система */
  os?: string;
  /** архитектура операционной системы */
  osArch?: string;
  /** версия ядра операционной системы */
  osKernelVersion?: string;
  /** семейство операционной системы */
  osType?: string;
  /** версия операционной системы */
  osVersion?: string;
}
