/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Monitoring Agent API
 * OpenAPI spec version: 1.0
 */
import type { PhysicalMemoryInfo } from './physicalMemoryInfo';

export interface MemorySpecs {
  /** физические плашки памяти */
  physicalMemoryList?: PhysicalMemoryInfo[];
  /** общий объем памяти */
  total?: number;
}
